package libManage;

import Models.User;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 * @author Jeremy Hudson
 * @author Charles Brady
 *
 * This class is used as a gateway to the rest of the program, where users can
 * open the database to search, or login as a customer or librarian
 *
 *
 * Last updated 2/20
 */
public class LibraryManagementGUI extends javax.swing.JFrame {

    /**
     * Creates new form LibraryManagementGUI
     */
    
    public LibraryManagementGUI() {
        initComponents();
        this.setTitle("Library Management System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LibManageSys = new javax.swing.JPanel();
        selectUserTypeLbl = new javax.swing.JLabel();
        exitProgramButton = new javax.swing.JButton();
        searchDatabaseNoLogin = new javax.swing.JLabel();
        searchDatabaseNoLoginButton = new javax.swing.JButton();
        Register_Button = new javax.swing.JButton();
        Login_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LibManageSys.setBorder(javax.swing.BorderFactory.createTitledBorder("Library Management System"));

        selectUserTypeLbl.setText("New User");

        exitProgramButton.setText("Exit Program");
        exitProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitProgramButtonActionPerformed(evt);
            }
        });

        searchDatabaseNoLogin.setText("Search database ");

        searchDatabaseNoLoginButton.setText("Open Database");
        searchDatabaseNoLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDatabaseNoLoginButtonActionPerformed(evt);
            }
        });

        Register_Button.setText("Register");
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });

        Login_Button.setText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Returning User");

        javax.swing.GroupLayout LibManageSysLayout = new javax.swing.GroupLayout(LibManageSys);
        LibManageSys.setLayout(LibManageSysLayout);
        LibManageSysLayout.setHorizontalGroup(
            LibManageSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LibManageSysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LibManageSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitProgramButton)
                    .addGroup(LibManageSysLayout.createSequentialGroup()
                        .addGroup(LibManageSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(LibManageSysLayout.createSequentialGroup()
                                .addGroup(LibManageSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchDatabaseNoLogin)
                                    .addComponent(jLabel1))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LibManageSysLayout.createSequentialGroup()
                                .addComponent(selectUserTypeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(8, 8, 8)
                        .addGroup(LibManageSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchDatabaseNoLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Register_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Login_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        LibManageSysLayout.setVerticalGroup(
            LibManageSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LibManageSysLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(LibManageSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_Button)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(LibManageSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDatabaseNoLogin)
                    .addComponent(searchDatabaseNoLoginButton))
                .addGap(18, 18, 18)
                .addGroup(LibManageSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectUserTypeLbl)
                    .addComponent(Register_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(exitProgramButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LibManageSys, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LibManageSys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        LibManageSys.getAccessibleContext().setAccessibleName("\"LMS\"");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitProgramButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitProgramButtonActionPerformed

    private void searchDatabaseNoLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDatabaseNoLoginButtonActionPerformed

        JFrame frame = new JFrame("Book DB view");
        BookDatabaseView BookDBView = new BookDatabaseView();
        frame.add(BorderLayout.CENTER, BookDBView);
        BookDBView.setPreferredSize(new Dimension(800, 800));
        frame.pack();
        frame.setVisible(true);

        BookDBView.setVisible(true);

    }//GEN-LAST:event_searchDatabaseNoLoginButtonActionPerformed

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed

        
        RegisterView libReg = new RegisterView("Customer");

        this.setVisible(false);

        libReg.setVisible(true);

    }//GEN-LAST:event_Register_ButtonActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        JFrame frame = new JFrame("Login");
        Login log = new Login();
        frame.add(BorderLayout.CENTER, log);
        frame.pack();
        frame.setVisible(true);
        this.setVisible(false);

        log.setVisible(true);
    }//GEN-LAST:event_Login_ButtonActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LibManageSys;
    private javax.swing.JButton Login_Button;
    private javax.swing.JButton Register_Button;
    private javax.swing.JButton exitProgramButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel searchDatabaseNoLogin;
    private javax.swing.JButton searchDatabaseNoLoginButton;
    private javax.swing.JLabel selectUserTypeLbl;
    // End of variables declaration//GEN-END:variables
}
