package Views;

import API.APITranslator;
import Controllers.BooksController;
import Models.BooksModel;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Charles Brady
 *
 * Last Updated 3/13
 *
 *
 * This is the view for the librarian to add a book to the database
 */
public class AddBookView extends javax.swing.JFrame {

    /**
     * Creates new form AddBookView
     */
    public AddBookView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchButtonAddBookView = new javax.swing.JButton();
        authorLabelAddBook = new javax.swing.JLabel();
        authorTextFieldAddBook = new javax.swing.JTextField();
        bookNameAddBookView = new javax.swing.JLabel();
        bookTextFieldAddBook = new javax.swing.JTextField();
        ISBNtxtfieldAddBookView = new javax.swing.JTextField();
        addBookISBNLbl = new javax.swing.JLabel();
        getAllMatchingResultsAddBookViewLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ISBN:");

        searchButtonAddBookView.setText("Add Book(s) to Local Database");
        searchButtonAddBookView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonAddBookViewActionPerformed(evt);
            }
        });

        authorLabelAddBook.setText("Author:");

        bookNameAddBookView.setText("Book Name:");

        addBookISBNLbl.setText("Add Individual book by ISBN");

        getAllMatchingResultsAddBookViewLbl.setText("Add all matching results by author/ book name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchButtonAddBookView))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBookISBNLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(getAllMatchingResultsAddBookViewLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ISBNtxtfieldAddBookView, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bookNameAddBookView)
                                .addGap(18, 18, 18)
                                .addComponent(bookTextFieldAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(authorLabelAddBook)
                                .addGap(29, 29, 29)
                                .addComponent(authorTextFieldAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBookISBNLbl)
                    .addComponent(getAllMatchingResultsAddBookViewLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(ISBNtxtfieldAddBookView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authorLabelAddBook)
                            .addComponent(authorTextFieldAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookNameAddBookView)
                            .addComponent(bookTextFieldAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(searchButtonAddBookView)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/* This will search the api for the book to obtain information,
 *  and then add the book to the database.
*/
    private void searchButtonAddBookViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonAddBookViewActionPerformed
           try {
               AddBookView addBookView = new AddBookView();
               BooksModel bookModel = new BooksModel();
               BooksController bookController = 
                       new BooksController(bookModel, addBookView);
               bookController.addBook(authorTextFieldAddBook.getText()
                       , bookTextFieldAddBook.getText(), 
                       ISBNtxtfieldAddBookView.getText());
             

        } catch (Exception ex) {
            Logger.getLogger(BookDatabaseView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_searchButtonAddBookViewActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBNtxtfieldAddBookView;
    private javax.swing.JLabel addBookISBNLbl;
    private javax.swing.JLabel authorLabelAddBook;
    private javax.swing.JTextField authorTextFieldAddBook;
    private javax.swing.JLabel bookNameAddBookView;
    private javax.swing.JTextField bookTextFieldAddBook;
    private javax.swing.JLabel getAllMatchingResultsAddBookViewLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchButtonAddBookView;
    // End of variables declaration//GEN-END:variables
}
