/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.event.ActionListener;

/**
 *
 * @author DELL6420
 */
public class BookDatabaseView extends javax.swing.JPanel {

    /**
     * Creates new form BookDatabaseView1
     */
    public BookDatabaseView() {
        initComponents();
    }
      public void searchDBListener(ActionListener listenForSearch) {

        searchLocalDatabaseButton.addActionListener(listenForSearch);

    }

    public String getAuthorName() {
        return searchAuthorNoLoginTxtFld.getText();
    }
    
      public String getBookTitle() {
        return searchTitleNoLoginTxtFld.getText();
    }
      
       public String getISBN() {
        return searchISBNNoLoginTxtFld.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LibManageSys2 = new javax.swing.JPanel();
        searchDatabaseNoLogin2 = new javax.swing.JLabel();
        searchAuthorNoLoginTxtFld2 = new javax.swing.JTextField();
        searchTitleNoLoginTxtFld2 = new javax.swing.JTextField();
        searchISBNNoLoginTxtFld2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        searchLocalDatabaseButton = new javax.swing.JButton();

        LibManageSys2.setBorder(javax.swing.BorderFactory.createTitledBorder("Library Management System"));

        searchDatabaseNoLogin2.setText("Search database ");

        searchAuthorNoLoginTxtFld2.setText("Author Name");

        searchTitleNoLoginTxtFld2.setText("Title of Book");

        jLabel3.setText("Search by ISBN");

        javax.swing.GroupLayout LibManageSys2Layout = new javax.swing.GroupLayout(LibManageSys2);
        LibManageSys2.setLayout(LibManageSys2Layout);
        LibManageSys2Layout.setHorizontalGroup(
            LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LibManageSys2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LibManageSys2Layout.createSequentialGroup()
                        .addComponent(searchDatabaseNoLogin2)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LibManageSys2Layout.createSequentialGroup()
                        .addGroup(LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchAuthorNoLoginTxtFld2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(searchTitleNoLoginTxtFld2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(searchISBNNoLoginTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 45, Short.MAX_VALUE))))
        );
        LibManageSys2Layout.setVerticalGroup(
            LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LibManageSys2Layout.createSequentialGroup()
                .addGroup(LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDatabaseNoLogin2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LibManageSys2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchAuthorNoLoginTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchISBNNoLoginTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchTitleNoLoginTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        searchLocalDatabaseButton.setText("Search Database");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LibManageSys2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchLocalDatabaseButton)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LibManageSys2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(searchLocalDatabaseButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LibManageSys;
    private javax.swing.JPanel LibManageSys1;
    private javax.swing.JPanel LibManageSys2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField searchAuthorNoLoginTxtFld;
    private javax.swing.JTextField searchAuthorNoLoginTxtFld1;
    private javax.swing.JTextField searchAuthorNoLoginTxtFld2;
    private javax.swing.JLabel searchDatabaseNoLogin;
    private javax.swing.JLabel searchDatabaseNoLogin1;
    private javax.swing.JLabel searchDatabaseNoLogin2;
    private javax.swing.JTextField searchISBNNoLoginTxtFld;
    private javax.swing.JTextField searchISBNNoLoginTxtFld1;
    private javax.swing.JTextField searchISBNNoLoginTxtFld2;
    private javax.swing.JButton searchLocalDatabaseButton;
    private javax.swing.JTextField searchTitleNoLoginTxtFld;
    private javax.swing.JTextField searchTitleNoLoginTxtFld1;
    private javax.swing.JTextField searchTitleNoLoginTxtFld2;
    // End of variables declaration//GEN-END:variables
}
