/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author DELL6420
 */
public class IndividualLibrarianView extends javax.swing.JPanel {

    /**
     * Creates new form IndividualLibrarianView
     */
    public IndividualLibrarianView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        individualLibrarianViewNameTxtLbl = new javax.swing.JLabel();
        individualLibrarianViewEmailTxtLbl = new javax.swing.JLabel();
        individualLibrarianViewLibCardNumberTxtLbl = new javax.swing.JLabel();
        individualLibrarianViewCheckoutsTxtLbl = new javax.swing.JLabel();
        individualLibrarianViewComboBox = new javax.swing.JComboBox<>();
        LibrarianNamePlaceholderTxtLbl = new javax.swing.JLabel();
        LibrarianEmailAddressPlaceholderTxtLbl = new javax.swing.JLabel();
        LibrarianLibraryCardNumberPlaceholderTxtLbl = new javax.swing.JLabel();
        individualCustomerViewBackButton = new javax.swing.JButton();
        individualLibrarianViewIDNumberTxtLbl = new javax.swing.JLabel();
        individualCustomerViewExiProgramButton = new javax.swing.JButton();
        LibrarianIDNumberPlaceholderTxtLbl = new javax.swing.JLabel();
        individualCustomerViewTxtLbl = new javax.swing.JLabel();

        individualLibrarianViewNameTxtLbl.setText("Librarian Name:");

        individualLibrarianViewEmailTxtLbl.setText("Librarian Email Address:");

        individualLibrarianViewLibCardNumberTxtLbl.setText("Librarian Library Card Number:");

        individualLibrarianViewCheckoutsTxtLbl.setText("Books Librarian has checked out:");

        individualLibrarianViewComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        individualLibrarianViewComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                individualLibrarianViewComboBoxActionPerformed(evt);
            }
        });

        LibrarianNamePlaceholderTxtLbl.setText("Librarian Name Placeholder");

        LibrarianEmailAddressPlaceholderTxtLbl.setText("Librarian Email Address Placeholder");

        LibrarianLibraryCardNumberPlaceholderTxtLbl.setText("Library Card Number Placeholder");

        individualCustomerViewBackButton.setText("Back");

        individualLibrarianViewIDNumberTxtLbl.setText("Librarian ID Number:");

        individualCustomerViewExiProgramButton.setText("Exit Program");

        LibrarianIDNumberPlaceholderTxtLbl.setText("Librarian ID Number Placeholder");

        individualCustomerViewTxtLbl.setText("Individual Librarian View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(individualCustomerViewExiProgramButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(individualCustomerViewBackButton)
                        .addGap(47, 47, 47)
                        .addComponent(individualCustomerViewTxtLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(individualLibrarianViewLibCardNumberTxtLbl)
                            .addComponent(individualLibrarianViewEmailTxtLbl)
                            .addComponent(individualLibrarianViewNameTxtLbl))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LibrarianNamePlaceholderTxtLbl)
                            .addComponent(LibrarianEmailAddressPlaceholderTxtLbl)
                            .addComponent(LibrarianLibraryCardNumberPlaceholderTxtLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(individualLibrarianViewCheckoutsTxtLbl)
                            .addComponent(individualLibrarianViewIDNumberTxtLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LibrarianIDNumberPlaceholderTxtLbl)
                            .addComponent(individualLibrarianViewComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(individualCustomerViewBackButton)
                    .addComponent(individualCustomerViewTxtLbl))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(individualLibrarianViewNameTxtLbl)
                    .addComponent(LibrarianNamePlaceholderTxtLbl))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(individualLibrarianViewEmailTxtLbl)
                    .addComponent(LibrarianEmailAddressPlaceholderTxtLbl))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(individualLibrarianViewLibCardNumberTxtLbl)
                    .addComponent(LibrarianLibraryCardNumberPlaceholderTxtLbl))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(individualLibrarianViewIDNumberTxtLbl)
                    .addComponent(LibrarianIDNumberPlaceholderTxtLbl))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(individualLibrarianViewCheckoutsTxtLbl)
                    .addComponent(individualLibrarianViewComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(individualCustomerViewExiProgramButton)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void individualLibrarianViewComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_individualLibrarianViewComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_individualLibrarianViewComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LibrarianEmailAddressPlaceholderTxtLbl;
    private javax.swing.JLabel LibrarianIDNumberPlaceholderTxtLbl;
    private javax.swing.JLabel LibrarianLibraryCardNumberPlaceholderTxtLbl;
    private javax.swing.JLabel LibrarianNamePlaceholderTxtLbl;
    private javax.swing.JButton individualCustomerViewBackButton;
    private javax.swing.JButton individualCustomerViewExiProgramButton;
    private javax.swing.JLabel individualCustomerViewTxtLbl;
    private javax.swing.JLabel individualLibrarianViewCheckoutsTxtLbl;
    private javax.swing.JComboBox<String> individualLibrarianViewComboBox;
    private javax.swing.JLabel individualLibrarianViewEmailTxtLbl;
    private javax.swing.JLabel individualLibrarianViewIDNumberTxtLbl;
    private javax.swing.JLabel individualLibrarianViewLibCardNumberTxtLbl;
    private javax.swing.JLabel individualLibrarianViewNameTxtLbl;
    // End of variables declaration//GEN-END:variables
}
