/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.BooksController;
import Controllers.UserController;
import Controllers.ViewsController;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import javax.swing.JFrame;

/**
 *
 * @author Charles Brady
 * @author Jeremy Hudson
 *
 * Last Updated 3/10
 *
 * This class allows the librarian to search the book database and to check the
 * books they have checked out, in addition to searching for and creating new
 * customers
 */
public class LibrarianView extends javax.swing.JFrame {

    ViewsController viewController = new ViewsController();
    
    /**
     * Creates new form NewJFrame
     */
    public LibrarianView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LibrarianLabel = new javax.swing.JLabel();
        BookSearchLabel = new javax.swing.JLabel();
        CustomerSearchLabel = new javax.swing.JLabel();
        AddBookLabel = new javax.swing.JLabel();
        AddLibrarianLabel = new javax.swing.JLabel();
        CheckInLabel = new javax.swing.JLabel();
        CheckOutLabel = new javax.swing.JLabel();
        CustomerSearchTextField = new javax.swing.JTextField();
        checkOutButton = new javax.swing.JButton();
        openDatabaseButton = new javax.swing.JButton();
        customerSearchButton = new javax.swing.JButton();
        addBookButton = new javax.swing.JButton();
        addLibrarianButton = new javax.swing.JButton();
        checkInButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        librarianViewCheckoutComboBox = new javax.swing.JComboBox<>();
        librarianViewGoToSelectedBookButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LibrarianLabel.setText("Librarian");

        BookSearchLabel.setText("Book Search:");

        CustomerSearchLabel.setText("Customer Search (ID):");

        AddBookLabel.setText("Add Book to Library");

        AddLibrarianLabel.setText("Add New Librarian");

        CheckInLabel.setText("Check In:");

        CheckOutLabel.setText("Check Out:");

        checkOutButton.setText("Check Out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        openDatabaseButton.setText("Open Database");
        openDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDatabaseButtonActionPerformed(evt);
            }
        });

        customerSearchButton.setText("Customer Search");
        customerSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerSearchButtonActionPerformed(evt);
            }
        });

        addBookButton.setText("Add Book");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        addLibrarianButton.setText("Add Librarian");
        addLibrarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLibrarianButtonActionPerformed(evt);
            }
        });

        checkInButton.setText("Check In");
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("My Check Outs:");

        librarianViewCheckoutComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        librarianViewGoToSelectedBookButton.setText("Go to selected book");
        librarianViewGoToSelectedBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianViewGoToSelectedBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(LibrarianLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerSearchLabel)
                            .addComponent(BookSearchLabel)
                            .addComponent(AddBookLabel)
                            .addComponent(AddLibrarianLabel)
                            .addComponent(CheckInLabel)
                            .addComponent(CheckOutLabel)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CustomerSearchTextField)
                            .addComponent(checkOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openDatabaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addLibrarianButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(librarianViewCheckoutComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerSearchButton)
                            .addComponent(librarianViewGoToSelectedBookButton))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LibrarianLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookSearchLabel)
                    .addComponent(openDatabaseButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerSearchLabel)
                    .addComponent(CustomerSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerSearchButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBookLabel)
                    .addComponent(addBookButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddLibrarianLabel)
                    .addComponent(addLibrarianButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInLabel)
                    .addComponent(checkInButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutLabel)
                    .addComponent(checkOutButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(librarianViewCheckoutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(librarianViewGoToSelectedBookButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
      viewController.determineView("AddBook");
    }//GEN-LAST:event_addBookButtonActionPerformed

    private void openDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDatabaseButtonActionPerformed
      viewController.determineView("SearchDB");

    }//GEN-LAST:event_openDatabaseButtonActionPerformed

    // Searches for customer within the database
    private void customerSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerSearchButtonActionPerformed
        try {
            String id = CustomerSearchTextField.getText();
//            UserController userControl = new UserController();
//            userControl.searchUser(id);

            //Code to display User
        } catch (Exception ex) {
            Logger.getLogger(LibrarianView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_customerSearchButtonActionPerformed

    // Opens the Register view with a librarian usertype in order to add a new librarian to the system
    private void addLibrarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLibrarianButtonActionPerformed
      viewController.determineView("AddLibrarian");
    }//GEN-LAST:event_addLibrarianButtonActionPerformed

    // Opens the Checkout view so the librarian can checkout a book for the customer
    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
             viewController.determineView("CheckoutView");

    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void librarianViewGoToSelectedBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianViewGoToSelectedBookButtonActionPerformed
          try {
//            BooksController bookController = new BooksController();
//            bookController.individualBookViewMethod
//            (TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY, TOOL_TIP_TEXT_KEY);
        } catch (Exception ex) {
            Logger.getLogger(CustomerView.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_librarianViewGoToSelectedBookButtonActionPerformed

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed

    }//GEN-LAST:event_checkInButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddBookLabel;
    private javax.swing.JLabel AddLibrarianLabel;
    private javax.swing.JLabel BookSearchLabel;
    private javax.swing.JLabel CheckInLabel;
    private javax.swing.JLabel CheckOutLabel;
    private javax.swing.JLabel CustomerSearchLabel;
    private javax.swing.JTextField CustomerSearchTextField;
    private javax.swing.JLabel LibrarianLabel;
    private javax.swing.JButton addBookButton;
    private javax.swing.JButton addLibrarianButton;
    private javax.swing.JButton checkInButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton customerSearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> librarianViewCheckoutComboBox;
    private javax.swing.JButton librarianViewGoToSelectedBookButton;
    private javax.swing.JButton openDatabaseButton;
    // End of variables declaration//GEN-END:variables
}
