package Views;

import Controllers.BooksController;
import Database.MySQLDBTranslator;
import Models.Books;
import Models.ManageBookInfo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Charles Brady
 *
 * Last Updated 3/13
 *
 *
 * This is the view for the librarian to add a book to the database
 */
public class AddBookView extends javax.swing.JFrame {

    /**
     * Creates new form AddBookView
     */
    public AddBookView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ISBNTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ISBN:");

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ISBNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(SearchButton)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ISBNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/* This will search the api for the book to obtain information,
 *  and then add the book to the database.
*/
    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        try {
            String isbn = ISBNTextField.getText();
            BooksController bookControl = new BooksController();
            Books book;
            ManageBookInfo mbi = new ManageBookInfo();

            if (isbn == null) {
                JOptionPane.showMessageDialog(null, "ISBN not given. Please try again.");
            } else {
                book = mbi.getRequestISBN(isbn);
                if (book != null) {
                    int result = bookControl.AddBook(book);
                    ISBNTextField.setText("");
                    // if book is successfully added, display Book Added dialog.
                    if (result > 0) {
                        JOptionPane.showMessageDialog(null, "Book Added.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Book not found.");
                    ISBNTextField.setText("");
                }

            }
        } catch (Exception ex) {
            Logger.getLogger(AddBookView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBNTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
