package Views;

import Models.Books;
import Models.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import Database.MySQLDBTranslator;

/**
 *
 * @author Charles Brady
 *
 * Last Updated 3/6
 *
 * This is the view for librarians to check out a customers book
 */
public class CheckoutView extends javax.swing.JFrame {

    /**
     * Creates new form CheckoutView
     */
    public CheckoutView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerTextField = new javax.swing.JTextField();
        ISBNTextField = new javax.swing.JTextField();
        CustomerLabel = new javax.swing.JLabel();
        BookISBNLabel = new javax.swing.JLabel();
        CheckoutButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CustomerLabel.setText("Customer:");

        BookISBNLabel.setText("Book ISBN:");

        CheckoutButton.setText("Checkout");
        CheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BookISBNLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckoutButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CustomerTextField)
                        .addComponent(ISBNTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISBNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookISBNLabel))
                .addGap(39, 39, 39)
                .addComponent(CheckoutButton)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutButtonActionPerformed

        String isbn = ISBNTextField.getText();
        String userID = CustomerTextField.getText();
        int id = Integer.valueOf(userID);

        Books book = new Books();
        User user = new User();

        try {
            MySQLDBTranslator translator = new MySQLDBTranslator();
            book.setISBN(isbn);
            user.setId(id);
            //  searchBooks(isbn);

        } catch (Exception ex) {
            Logger.getLogger(CheckoutView.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_CheckoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookISBNLabel;
    private javax.swing.JToggleButton CheckoutButton;
    private javax.swing.JLabel CustomerLabel;
    private javax.swing.JTextField CustomerTextField;
    private javax.swing.JTextField ISBNTextField;
    // End of variables declaration//GEN-END:variables
}
