package Views;

import Views.RegisterView;
import Views.BookDatabaseView;
import Models.User;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 * @author Jeremy Hudson
 * @author Charles Brady
 *
 * This class is used as a gateway to the rest of the program, where users can
 * open the database to search, or login as a customer or librarian
 *
 *
 * Last updated 3/16
 */
public class LibraryManagementGUIView extends javax.swing.JFrame {

    /**
     * Creates new form LibraryManagementGUI
     */
    public LibraryManagementGUIView() {
        initComponents();
        this.setTitle("Library Management System");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LibManageSys = new javax.swing.JPanel();
        selectUserTypeLbl = new javax.swing.JLabel();
        exitProgramButton = new javax.swing.JButton();
        searchDatabaseNoLogin = new javax.swing.JLabel();
        searchDatabaseNoLoginButton = new javax.swing.JButton();
        Register_Button = new javax.swing.JButton();
        Login_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LibManageSys.setBorder(javax.swing.BorderFactory.createTitledBorder("Library Management System"));
        LibManageSys.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectUserTypeLbl.setText("New User");
        LibManageSys.add(selectUserTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, -1));

        exitProgramButton.setText("Exit Program");
        exitProgramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitProgramButtonActionPerformed(evt);
            }
        });
        LibManageSys.add(exitProgramButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        searchDatabaseNoLogin.setText("Try without Login");
        LibManageSys.add(searchDatabaseNoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        searchDatabaseNoLoginButton.setText("Search Database");
        searchDatabaseNoLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDatabaseNoLoginButtonActionPerformed(evt);
            }
        });
        LibManageSys.add(searchDatabaseNoLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 76, -1, -1));

        Register_Button.setText("Register");
        Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_ButtonActionPerformed(evt);
            }
        });
        LibManageSys.add(Register_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 117, 115, -1));

        Login_Button.setText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        LibManageSys.add(Login_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 35, 115, -1));

        jLabel1.setText("Returning User");
        LibManageSys.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LibManageSys, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LibManageSys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LibManageSys.getAccessibleContext().setAccessibleName("\"LMS\"");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitProgramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitProgramButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitProgramButtonActionPerformed

    private void searchDatabaseNoLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDatabaseNoLoginButtonActionPerformed

        JFrame frame = new JFrame("Book DB view");
        BookDatabaseView BookDBView = new BookDatabaseView();
        frame.add(BorderLayout.CENTER, BookDBView);
        BookDBView.setPreferredSize(new Dimension(800, 800));
        frame.pack();
        frame.setVisible(true);

        BookDBView.setVisible(true);

    }//GEN-LAST:event_searchDatabaseNoLoginButtonActionPerformed

    private void Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_ButtonActionPerformed

        RegisterView libReg = new RegisterView("Customer");
        this.setVisible(false);
        libReg.setVisible(true);

    }//GEN-LAST:event_Register_ButtonActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        LoginView log = new LoginView();
        log.setVisible(true);
    }//GEN-LAST:event_Login_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LibManageSys;
    private javax.swing.JButton Login_Button;
    private javax.swing.JButton Register_Button;
    private javax.swing.JButton exitProgramButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel searchDatabaseNoLogin;
    private javax.swing.JButton searchDatabaseNoLoginButton;
    private javax.swing.JLabel selectUserTypeLbl;
    // End of variables declaration//GEN-END:variables
}
