package Views;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Charles Brady
 * @author Jeremy Hudson
 *
 * Last Updated 4-25-2019
 *
 * This is the view for the library card.
 */
public class LibraryCardView extends javax.swing.JFrame {

    /**
     * Creates new form LibraryCardView
     */
    public LibraryCardView() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barCode = new javax.swing.JButton();
        LibraryCardLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        printButtonLibCard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barCode.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        LibraryCardLabel.setText("Library Card");

        printButtonLibCard.setText("Print");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTextField)
                            .addComponent(barCode, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(printButtonLibCard))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(LibraryCardLabel)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LibraryCardLabel)
                .addGap(18, 18, 18)
                .addComponent(barCode, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printButtonLibCard)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void printListener(ActionListener listenForPrint) {

        this.printButtonLibCard.addActionListener(listenForPrint);

    }

    public void setNameField(String _name) {

        this.nameTextField.setText(_name);

    }

    public void setBarCode(ImageIcon _image) {

        this.barCode.setIcon(_image);
        this.pack();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LibraryCardLabel;
    private javax.swing.JButton barCode;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton printButtonLibCard;
    // End of variables declaration//GEN-END:variables
}
